"""Central paths and constants for the data cleaning pipeline."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

RAW_ROOT = PROJECT_ROOT / "data" / "raw"
PAD_UFES20_RAW_DIR = RAW_ROOT / "PAD_UFES20"
PAD_UFES20_METADATA_FILE = PAD_UFES20_RAW_DIR / "metadata.csv"
PAD_UFES20_IMAGE_SUBDIRS = ["imgs_part_1", "imgs_part_2", "imgs_part_3"]

HAM10000_RAW_DIR = RAW_ROOT / "HAM10000"
HAM10000_METADATA_FILE = HAM10000_RAW_DIR / "HAM10000_metadata.csv"
HAM10000_IMAGE_SUBDIRS = ["HAM10000_images_part_1", "HAM10000_images_part_2"]

ISIC1_RAW_DIR = RAW_ROOT / "ISIC_Archive_1"
ISIC1_SPLIT_SUBDIRS = ["Train", "Test"]

ISIC2_RAW_DIR = RAW_ROOT / "ISIC_Archive_2"
ISIC2_METADATA_FILE = ISIC2_RAW_DIR / "metadata.csv"
ISIC2_IMAGE_SUBDIRS = ["images"]

INTERIM_ROOT = PROJECT_ROOT / "data" / "interim"
PAD_UFES20_INTERIM_DIR = INTERIM_ROOT / "PAD_UFES20"
HAM10000_INTERIM_DIR = INTERIM_ROOT / "HAM10000"
ISIC1_INTERIM_DIR = INTERIM_ROOT / "ISIC_Archive_1"
ISIC2_INTERIM_DIR = INTERIM_ROOT / "ISIC_Archive_2"

PROCESSED_ROOT = PROJECT_ROOT / "data" / "processed"
PAD_UFES20_PROCESSED_DIR = PROCESSED_ROOT / "PAD_UFES20"
HAM10000_PROCESSED_DIR = PROCESSED_ROOT / "HAM10000"
ISIC1_PROCESSED_DIR = PROCESSED_ROOT / "ISIC_Archive_1"
ISIC2_PROCESSED_DIR = PROCESSED_ROOT / "ISIC_Archive_2"

LOGS_ROOT = PROJECT_ROOT / "logs"
PAD_UFES20_LOGS_DIR = LOGS_ROOT / "PAD_UFES20"
HAM10000_LOGS_DIR = LOGS_ROOT / "HAM10000"
ISIC1_LOGS_DIR = LOGS_ROOT / "ISIC_Archive_1"
ISIC2_LOGS_DIR = LOGS_ROOT / "ISIC_Archive_2"

# Fixed seed for the patient-wise / lesion-wise split, so results are reproducible.
SPLIT_SEED = 42
SPLIT_RATIOS = {"train": 0.70, "val": 0.15, "test": 0.15}

DATASET_SOURCE_NAME = "PAD_UFES20"
HAM10000_DATASET_SOURCE_NAME = "HAM10000"
ISIC1_DATASET_SOURCE_NAME = "ISIC_Archive_1"
ISIC2_DATASET_SOURCE_NAME = "ISIC_Archive_2"
